// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWO3hxU9IfAC3y2geMwP4f7nRMdUX0kNk',
    appId: '1:461250923898:web:5d08e3bf42662cc71adac3',
    messagingSenderId: '461250923898',
    projectId: 'hostmi-398612',
    authDomain: 'hostmi-398612.firebaseapp.com',
    storageBucket: 'hostmi-398612.appspot.com',
    measurementId: 'G-1RD5BGMBCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJKFJ5xqSm41Uwbe6XioUfeBKghkmsixU',
    appId: '1:461250923898:android:65daccd05383f48a1adac3',
    messagingSenderId: '461250923898',
    projectId: 'hostmi-398612',
    storageBucket: 'hostmi-398612.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvG-tikOqJIZVNXu9zz-bwTMCYBO7D0uE',
    appId: '1:461250923898:ios:0227c05e7bbf8ff51adac3',
    messagingSenderId: '461250923898',
    projectId: 'hostmi-398612',
    storageBucket: 'hostmi-398612.appspot.com',
    iosBundleId: 'com.hostmi.props.search',
  );
}
